name: mozais_theme_fallback
description: Minimal built-in fallback theme for the Mozais greeter.
publish_to: none

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  mozais_scene:
    path: ../mozais_scene
  mozais_greeter_components:
    path: ../mozais_greeter_components
  mozais_theme_sdk:
    path: ../mozais_theme_sdk

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  mozais_scene_codegen:
    path: ../mozais_scene_codegen

flutter:
  uses-material-design: true
