name: mozais_greeter
description: Compile-time themeable Flutter greeter for Mozais.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dbus: ^0.7.11
  mozais_scene:
    path: packages/mozais_scene

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mozais_scene_codegen:
    path: packages/mozais_scene_codegen

flutter:
  uses-material-design: true
  assets:
    - assets/
