name: mozais_scene_editor
description: "Visual editor for Mozais scene documents."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  mozais_greeter_ui:
    path: ../mozais_greeter_ui
  mozais_scene:
    path: ../mozais_scene
  mozais_scene_schema:
    path: ../mozais_scene_schema

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
