import 'dart:io';

const generatedDependenciesStart = '# BEGIN GENERATED THEME DEPENDENCIES';
const generatedDependenciesEnd = '# END GENERATED THEME DEPENDENCIES';

const _themePackagePrefix = 'mozais_theme_';

class ThemePackage {
  const ThemePackage({
    required this.packageName,
    required this.themeName,
    required this.builderName,
  });

  final String packageName;
  final String themeName;
  final String builderName;

  String get relativePath => 'packages/$packageName';
}

List<ThemePackage> findThemePackages(Directory repoRoot) {
  final packagesDirectory = Directory(_join(repoRoot.path, 'packages'));
  if (!packagesDirectory.existsSync()) {
    throw StateError('Missing packages directory: ${packagesDirectory.path}');
  }

  final themes = <ThemePackage>[];
  for (final directory
      in packagesDirectory
          .listSync(followLinks: false)
          .whereType<Directory>()) {
    final packageName = _lastSegment(directory.path);
    if (!packageName.startsWith(_themePackagePrefix)) {
      continue;
    }

    final themeName = packageName.substring(_themePackagePrefix.length);
    if (!RegExp(r'^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$').hasMatch(themeName)) {
      throw FormatException(
        'Theme package $packageName must use a lowercase underscore name.',
      );
    }

    final libDirectory = Directory(_join(directory.path, 'lib'));
    final entrypoint = File(_join(libDirectory.path, 'theme.dart'));
    final sceneFiles = libDirectory.existsSync()
        ? libDirectory
              .listSync(recursive: true, followLinks: false)
              .whereType<File>()
              .where((file) => file.path.endsWith('.scene.json'))
              .toList()
        : const <File>[];
    if (!entrypoint.existsSync() || sceneFiles.isEmpty) {
      continue;
    }

    final builderName = _builderName(themeName);
    final entrypointSource = entrypoint.readAsStringSync();
    if (!RegExp(r'\b' + RegExp.escape(builderName) + r'\s*\(')
        .hasMatch(entrypointSource)) {
      throw FormatException(
        '$packageName must export $builderName() from lib/theme.dart.',
      );
    }
    themes.add(
      ThemePackage(
        packageName: packageName,
        themeName: themeName,
        builderName: builderName,
      ),
    );
  }

  themes.sort((left, right) => left.packageName.compareTo(right.packageName));
  final names = <String>{};
  for (final theme in themes) {
    if (!names.add(theme.themeName)) {
      throw StateError('Duplicate theme name: ${theme.themeName}');
    }
  }
  for (final requiredName in ['default', 'fallback']) {
    if (!names.contains(requiredName)) {
      throw StateError(
        'The theme catalog requires mozais_theme_$requiredName.',
      );
    }
  }
  return themes;
}

void writeThemeCatalog({
  required Directory repoRoot,
  required List<ThemePackage> themes,
}) {
  final catalogDirectory = Directory(
    _join(repoRoot.path, 'packages/mozais_theme_catalog'),
  );
  final pubspec = File(_join(catalogDirectory.path, 'pubspec.yaml'));
  if (!pubspec.existsSync()) {
    throw StateError('Missing theme catalog pubspec: ${pubspec.path}');
  }
  pubspec.writeAsStringSync(
    _withGeneratedDependencies(pubspec.readAsStringSync(), themes),
  );

  final registry = File(
    _join(catalogDirectory.path, 'lib/src/theme_registry.g.dart'),
  );
  registry.writeAsStringSync(generateThemeRegistry(themes));
}

String generateThemeRegistry(List<ThemePackage> themes) {
  final imports = StringBuffer()
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln("import 'package:mozais_theme_sdk/mozais_theme_sdk.dart';");
  for (final theme in themes) {
    imports.writeln(
      "import 'package:${theme.packageName}/theme.dart' show ${theme.builderName};",
    );
  }

  final builders = themes
      .map(
        (theme) =>
            "    '${theme.themeName}': ({Color? seed}) => ${theme.builderName}(seed: seed),",
      )
      .join('\n');
  return '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/theme_catalog.dart.
$imports
typedef ThemeBuilder = ThemeDefinition Function({Color? seed});

class ThemeRegistry {
  const ThemeRegistry._();

  static const defaultThemeName = 'default';
  static const fallbackThemeName = 'fallback';

  static final Map<String, ThemeBuilder> _builders = <String, ThemeBuilder>{
$builders
  };

  static ThemeDefinition resolve(String name, {Color? seed}) {
    assert(
      _builders.containsKey(name),
      'Unknown MOZAIS_THEME "\$name"; falling back to \$fallbackThemeName.',
    );
    final builder = _builders[name] ?? _builders[fallbackThemeName]!;
    return builder(seed: seed);
  }

  /// Samples the theme background for a dynamic palette seed.
  ///
  /// Returns null when the theme has no image background or the asset cannot
  /// be decoded, in which case the caller keeps the built-in seed.
  static Future<Color?> findBackgroundSeed(ThemeDefinition theme) async {
    final asset = theme.document.background.asset;
    if (asset == null) {
      return null;
    }
    try {
      return await extractSeed(asset);
    } on Object {
      return null;
    }
  }
}
''';
}

String _withGeneratedDependencies(String pubspec, List<ThemePackage> themes) {
  final start = pubspec.indexOf(generatedDependenciesStart);
  final end = pubspec.indexOf(
    generatedDependenciesEnd,
    start < 0 ? 0 : start + generatedDependenciesStart.length,
  );
  if (start < 0 || end < 0) {
    throw StateError(
      'Theme catalog pubspec is missing generated dependency markers.',
    );
  }

  final block = StringBuffer()..writeln(generatedDependenciesStart);
  for (final theme in themes) {
    block
      ..writeln('  ${theme.packageName}:')
      ..writeln('    path: ../${theme.packageName}');
  }
  block.write('  $generatedDependenciesEnd');
  return pubspec.replaceRange(
    start,
    end + generatedDependenciesEnd.length,
    block.toString(),
  );
}

String _builderName(String themeName) {
  final words = themeName.split('_');
  final pascalName = words
      .map((word) => '${word[0].toUpperCase()}${word.substring(1)}')
      .join();
  return 'build${pascalName}Theme';
}

String _lastSegment(String path) {
  return path.split(Platform.pathSeparator).last;
}

String _join(String base, String relative) {
  return '$base${Platform.pathSeparator}${relative.replaceAll('/', Platform.pathSeparator)}';
}
