// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/theme_catalog.dart.
import 'package:flutter/material.dart';
import 'package:mozais_theme_sdk/mozais_theme_sdk.dart';
import 'package:mozais_theme_default/theme.dart' show buildDefaultTheme;
import 'package:mozais_theme_fallback/theme.dart' show buildFallbackTheme;

typedef ThemeBuilder = ThemeDefinition Function({Color? seed});

class ThemeRegistry {
  const ThemeRegistry._();

  static const defaultThemeName = 'default';
  static const fallbackThemeName = 'fallback';

  static final Map<String, ThemeBuilder> _builders = <String, ThemeBuilder>{
    'default': ({Color? seed}) => buildDefaultTheme(seed: seed),
    'fallback': ({Color? seed}) => buildFallbackTheme(seed: seed),
  };

  static ThemeDefinition resolve(String name, {Color? seed}) {
    assert(
      _builders.containsKey(name),
      'Unknown MOZAIS_THEME "$name"; falling back to $fallbackThemeName.',
    );
    final builder = _builders[name] ?? _builders[fallbackThemeName]!;
    return builder(seed: seed);
  }

  /// Samples the theme background for a dynamic palette seed.
  ///
  /// Returns null when the theme has no image background or the asset cannot
  /// be decoded, in which case the caller keeps the built-in seed.
  static Future<Color?> findBackgroundSeed(ThemeDefinition theme) async {
    final asset = theme.document.background.asset;
    if (asset == null) {
      return null;
    }
    try {
      return await extractSeed(asset);
    } on Object {
      return null;
    }
  }
}
